version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: ./client/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000" 
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
