import type { Metadata } from "next";
import { PrimeReactProvider } from 'primereact/api';
import "./globals.css";
import 'mapbox-gl/dist/mapbox-gl.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
